<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>征信评分系统</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link type="text/css" rel="stylesheet" href="http://ultracharm.oss-cn-shanghai.aliyuncs.com/web_resources/css/semantic.min.css" />
  <script src='http://ultracharm.oss-cn-shanghai.aliyuncs.com/web_resources/scripts/jquery.min.js' type='text/javascript'></script>
  <script src='http://ultracharm.oss-cn-shanghai.aliyuncs.com/web_resources/scripts/semantic.min.js' type='text/javascript'></script>
  
  <!-- inject:css -->
  <!-- endinject -->
</head>
<body>
<div class="ui horizontal divider"></div>
<div class="ui centered grid">


<div class="twelve wide column">
<form class="ui form" method="post">
    <div class="four fields">
        <div class="required field">
            <input type="text" name="name" placeholder="姓名" >
        </div>
        <div class="required field">
            <input type="text" name="idcard_no" placeholder="身份证号" >
        </div>
        <div class="required field">
            <input type="number" name="phone" placeholder="手机号"  >
        </div>
        <div class="required field">
            <input type="text" name="area" placeholder="居住地"  >
        </div>        
    </div>
    <div class="four fields">
        <div class="required field">
        	<label>有无重大疾病</label>
            <select name="has_disease" class="ui dropdown" id="has_disease">
           		<option value=""></option>
            	<option value="1">无</option>
            	<option value="2">有</option>
            </select>
        </div>
        <div class="required field">
        	<label>婚姻状况</label>
            <select name="marriage_status" class="ui dropdown" id="marriage_status">
            	<option value=""></option>
            	<option value="1">未婚</option>
            	<option value="2">已婚</option>
            	<option value="3">离婚</option>
            </select>
        </div>
        <div class="required field">
        	<label>有无子女</label>
            <select name="has_kids" class="ui dropdown" id="has_kids">
            	<option value=""></option>
            	<option value="1">无</option>
            	<option value="2">有</option>
            </select>
        </div>
        <div class="required field">
        	<label>是否给父母赡养费</label>
            <select name="give_alimony" class="ui dropdown" id="give_alimony">
            	<option value=""></option>
            	<option value="1">否</option>
            	<option value="2">是</option>
            </select>
        </div>
    </div> 
    <div class="four fields">
        <div class="required field">
        	<label>学历</label>
            <select name="education" class="ui dropdown" id="education">
           		<option value=""></option>
            	<option value="1">高中以下</option>
            	<option value="2">高中</option>
            	<option value="3">专科</option>
            	<option value="4">本科</option>
            	<option value="5">本科以上</option>
            </select>
        </div>
        <div class="required field">
        	<label>驾照</label>
            <select name="drive_license" class="ui dropdown" id="drive_license">
            	<option value=""></option>
            	<option value="1">无</option>
            	<option value="2">有</option>
            </select>
        </div>
        <div class="required field">
        	<label>工作属性</label>
            <select name="job" class="ui dropdown" id="job">
            	<option value=""></option>
            	<option value="1">无业</option>
            	<option value="2">事业单位</option>
            	<option value="3">外资企业</option>
            	<option value="4">私营企业</option>
            </select>
        </div>
        <div class="required field">
        	<label>月薪</label>
            <input type="number" name="salary">
        </div>
    </div> 
    <div class="four fields">
        <div class="required field">
        	<label>芝麻信用分</label>
            <input type="number" name="alipay_score">
        </div>
        <div class="required field">
        	<label>是否有房</label>
            <select name="house" class="ui dropdown" id="house">
            	<option value=""></option>
            	<option value="1">无</option>
            	<option value="2">有</option>
            </select>
        </div>
        <div class="required field">
        	<label>是否有车</label>
            <select name="car" class="ui dropdown" id="car">
            	<option value=""></option>
            	<option value="1">无</option>
            	<option value="2">有</option>
            </select>
        </div>
        <div class="required field">
        	<label>个人爱好</label>
            <select name="interest" class="ui dropdown" id="interest">
            	<option value=""></option>
            	<option value="1">无</option>
            	<option value="2">字画戏曲</option>
            	<option value="3">旅游摄影</option>
            	<option value="4">棋牌游戏</option>
            </select>
        </div>
    </div> 
    <div class="four fields">
        <div class="required field">
        	<label>居住证积分</label>
            <input type="number" name="resident_score">
        </div>
        <div class="required field">
        	<label>家庭担保人</label>
            <select name="has_guarantor" class="ui dropdown" id="has_guarantor">
            	<option value=""></option>
            	<option value="1">无</option>
            	<option value="2">有</option>
            </select>
        </div>
    </div> 
    <div class="required field">
        <div class="ui checkbox">
            <input type="checkbox" name="user_agreement">
            <label>本人保证以上所填信息真实有效，如有虚假或欺诈自愿承担民事及刑事责任</label>
        </div>
    </div>
    <div class="ui primary submit button">提交</div>
        <div class="ui error message"></div>
    </form>
    </div>
    </div>
</div>

<script>
<?php if (!empty($score_description)): ?>
alert('<?php echo $score_description; ?>');
<?php endif; ?>

$.fn.form.settings.prompt.empty = '{name} 是必填项';
$.fn.form.settings.prompt.integer = '{name} 必须是数字';
$.fn.form.settings.prompt.checked = '必须勾选 {name}';
$.fn.form.settings.prompt.exactLength = '{name} 长度必须为 {ruleValue}';

$(document).ready(function (){
    $('.ui.form').form({
        fields:{
            name: 'empty',
            idcard_no: 'empty',
            phone: ['empty', 'exactLength[11]', 'integer'],
            area: 'empty',

            has_disease: 'empty',
            marriage_status: 'empty',
            has_kids: 'empty',
            give_alimony: 'empty',

            education: 'empty',
            drive_license: 'empty',
            job: 'empty',
            salary: ['empty', 'integer'],

            alipay_score: ['empty', 'integer'],
            house: 'empty',
            car: 'empty',
            interest: 'empty',

            resident_score: ['empty', 'integer'],
            has_guarantor: 'empty',
            
            user_agreement: 'checked'

        }
    });
});
</script>
</body>
</html>
